Repository 2025-HERETHON/2025-herethon-21, pull requests merged in 2025-07, with the labels that each got.

#14 Issue/PR 템플릿 수정, LANGUAGE_CODE 수정
  .github/ISSUE_TEMPLATE/bug_report_brief.md
  .github/ISSUE_TEMPLATE/bug_report_detail.md
  .github/ISSUE_TEMPLATE/todo_backend.md
  .github/ISSUE_TEMPLATE/todo_frontend.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
  HERE/settings.py
Labels: document📝, refactor♻️

#15 환경변수 설정
  .env.example
  HERE/settings.py
  env.py
Labels: feature✨, setting⚙

#25 달력 컴포넌트, 전체페이지 활용 컴포넌트, 마이페이지 추가
  frontend/urls.py
  frontend/views.py
  static/assets/img/Group.png
  static/assets/img/logo.png
  static/assets/폴더 업로드용 임시 파일
  static/functions/component_functions/calendar_component.js
  static/styles/component_styles/calendar_component.css
  static/styles/component_styles/page_component.css
  static/styles/page_styles/mypage.css
  templates/components/calendar_component.html
  templates/components/page_component.html
  templates/pages/component_calendar.html
  templates/pages/component_page.html
  templates/pages/mypage.html
Labels: design💄, feature✨

#34 #33 CustomUser 모델 수정
  accounts/models.py
Labels: development🔨, refactor♻️

#36 ResponseHelper 추가
  utils/helpers.py
Labels: development🔨, feature✨

#66 왼쪽 페이지 반응형 , 친구 페이지 더미데이터 , 추가 / 검색 버튼 기능
  frontend/views.py
  static/assets/img/happy_pipi.png
  static/assets/img/sad_pipi.png
  static/functions/page_functions/cycle_page.js
  static/functions/page_functions/edit_page.js
  static/functions/page_functions/period_page.js
  static/functions/page_functions/scrap_page.js
  static/styles/component_styles/calendar_component.css
  static/styles/component_styles/header_component.css
  static/styles/component_styles/page_component.css
  static/styles/page_styles/cycle.css
  static/styles/page_styles/edit_page.css
  static/styles/page_styles/mypage_main.css
  static/styles/page_styles/onboarding_pages/last_menstruation_page.css
  static/styles/page_styles/page_common.css
  static/styles/page_styles/scrap.css
  templates/components/friendbox_component.html
  templates/components/infobox_friend.html
  templates/pages/friend_page.html
Labels: design💄, refactor♻️

#68 버튼 연결 수정
  static/functions/page_functions/finished_routine.js
  templates/components/header_component.html
  templates/pages/alarm_page.html
  templates/pages/finished_routine.html
  templates/pages/make_friends_pages/friended.html
Labels: design💄, refactor♻️

#71 스크랩, 월경페이지 삭제기능 구현, 스크랩 루틴 클릭시 이동 추가
  static/functions/page_functions/period_page.js
  static/functions/page_functions/scrap_page.js
  static/styles/page_styles/scrap.css
Labels: design💄, refactor♻️

#47 예외 처리 추가
  HERE/settings.py
  templates/error/500.html
  utils/exceptions.py
  utils/helpers.py
  utils/middleware.py
  utils/validators.py
Labels: development🔨, feature✨

#48 menstruations 앱 services 추가
  accounts/migrations/0001_initial.py
  conditionreviews/migrations/0001_initial.py
  exercises/migrations/0001_initial.py
  exercises/migrations/0002_alter_exercisehistory_options_and_more.py
  friends/migrations/0001_initial.py
  menstruations/forms.py
  menstruations/migrations/0001_initial.py
  menstruations/models.py
  menstruations/services.py
  menstruations/templates/test.html
  menstruations/templates/test_create_menstruation.html
  menstruations/urls.py
  menstruations/views.py
  notifications/migrations/0001_initial.py
Labels: development🔨, feature✨

#75 #74 notifications add
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_customuser_bio.py
  accounts/migrations/0003_alter_customuser_profile_image.py
  accounts/migrations/0004_alter_customuser_nickname.py
  conditionreviews/migrations/0001_initial.py
  conditionreviews/migrations/0002_alter_conditionreview_rating.py
  exercises/migrations/0001_initial.py
  exercises/migrations/0003_alter_reactedexercisereview_emoji.py
  friends/migrations/0001_initial.py
  friends/services.py
  friends/views.py
  menstruations/migrations/0001_initial.py
  notifications/migrations/0001_initial.py
Labels: development🔨, feature✨

#78 데이터베이스 최종 마이그레이션, NANOIDField 라이브러리 제거
  accounts/migrations/0001_initial.py
  accounts/models.py
  conditionreviews/migrations/0001_initial.py
  exercises/migrations/0001_initial.py
  friends/migrations/0001_initial.py
  menstruations/migrations/0001_initial.py
  notifications/migrations/0001_initial.py
  requirements.txt
Labels: development🔨, refactor♻️

#94 83 pages exercises
  core/context_processors.py
  frontend/views.py
  static/assets/img/emoji/angry.png
  static/assets/img/emoji/close.png
  static/assets/img/emoji/open.png
  static/assets/img/emoji/sad.png
  static/assets/img/emoji/smile.png
  static/functions/component_functions/calendar_basic.js
  static/functions/component_functions/calendar_component.js
  static/functions/page_functions/cycle_page.js
  static/functions/page_functions/routine_ing_component.js
  static/functions/page_functions/scrap_page.js
  templates/components/reviewed_review_component.html
  templates/components/routine_list_component.html
  templates/pages/cycle_page.html
  templates/pages/edit_page.html
  templates/pages/friend_page.html
  templates/pages/mypage_main.html
  templates/pages/period_page.html
  templates/pages/rest_page.html
  templates/pages/routine_ing_page.html
  templates/pages/scrap_page.html
Labels: development🔨, feature✨

#96 #85 페이지 연결
  accounts/services.py
  accounts/templates/login.html
  accounts/templates/main.html
  accounts/templates/signup.html
  accounts/urls.py
  accounts/views.py
  conditionreviews/services.py
  conditionreviews/urls.py
  conditionreviews/views.py
  friends/views.py
  frontend/urls.py
  frontend/views.py
  static/functions/component_functions/condition_component.js
  static/functions/component_functions/header_component.js
  static/functions/component_functions/signup_component.js
  static/functions/page_functions/edit_page.js
  templates/components/condition_component.html
  templates/components/header_component.html
  templates/components/infobox_component.html
  templates/components/login_component.html
  templates/components/signup_component.html
  templates/example/base.html
  templates/pages/edit_page.html
  templates/pages/make_friends_pages/friended.html
  templates/pages/make_friends_pages/friends_confirm.html
  templates/pages/make_friends_pages/friends_email_input.html
  templates/pages/onboarding_pages/purpose_page.html
  utils/constants.py
Labels: development🔨, feature✨
