Repository 2025-HERETHON/2025-herethon-21, pull requests merged in 2025-09, with the labels that each got.

#104 User 모델 수정
  accounts/forms.py
  accounts/migrations/0002_alter_customuser_exercise_goal_and_more.py
  accounts/models.py
  exercises/services.py
  exercises/views.py
  friends/urls.py
  friends/views.py
  frontend/urls.py
  frontend/views.py
  notifications/services.py
  notifications/templates/test.html
  notifications/urls.py
  notifications/views.py
  templates/pages/alarm_page.html
  templates/pages/friend_page.html
  templates/pages/make_friends_pages/friends_confirm.html
  utils/constants.py
Labels: development🔨, refactor♻️

#106 주기별 페이지 슬라이더 타이머 60분이 0분으로 처리되는 오류 수정, 운동방 페이지 스크랩 버튼 삭제, 월경 내역 하나만 남았을 시 삭제버튼 숨김 + 연동 미완료 페이지들 JS 최소화
  static/functions/page_functions/alarm_page.js
  static/functions/page_functions/finished_routine.js
  static/functions/page_functions/make_friends_pages/friended.js
  static/functions/page_functions/make_friends_pages/friends_confirm.js
  static/functions/page_functions/make_friends_pages/friends_email_input.js
  static/functions/page_functions/onboarding_pages/onboarding_3.js
  static/styles/page_styles/cycle.css
  static/styles/page_styles/finished_routine.css
  static/styles/page_styles/make_friends_pages/friends_confirm.css
  templates/pages/alarm_page.html
  templates/pages/cycle_page.html
  templates/pages/finished_routine.html
  templates/pages/make_friends_pages/friended.html
  templates/pages/make_friends_pages/friends_confirm.html
  templates/pages/make_friends_pages/friends_email_input.html
  templates/pages/onboarding_pages/onboarding_3.html
  templates/pages/period_page.html
  templates/pages/routine_ing_page.html
Labels: bug🐛, design💄

#112 django.core.exceptions.FieldError: 'id' cannot be specified for CustomUser model form as it is a non-editable field 해결
  accounts/admin.py
  accounts/forms.py
  accounts/migrations/0003_remove_customuser_username_alter_customuser_id.py
  accounts/models.py
  accounts/views.py
  conditionreviews/models.py
  exercises/models.py
  friends/models.py
  friends/views.py
  frontend/views.py
  menstruations/models.py
  notifications/models.py
  notifications/services.py
  notifications/views.py
Labels: bug🐛, development🔨

#116 menstruations, exercises, notifications 앱의 GET 뷰 삭제에 따른 urls.py 수정
  exercises/urls.py
  menstruations/urls.py
  notifications/urls.py
Labels: bug🐛, development🔨

#118 base_side, base_side_left, base_side_right, favicon.ico 추가
  static/assets/img/favicon.ico
  static/styles/page_styles/base.css
  static/styles/page_styles/base_side.css
  static/styles/page_styles/base_side_right.css
  templates/example/base.html
  templates/example/base_side.html
  templates/example/base_side_left.html
  templates/example/base_side_right.html
Labels: design💄, feature✨

#125 불필요한 파일 삭제
  exercises/templates/test_exercise_end.html
  exercises/templates/test_exercise_start.html
  exercises/templates/test_exercises.html
  menstruations/templates/test.html
  menstruations/templates/test_create_menstruation.html
  notifications/templates/test.html
  static/폴더업로드용임시파일
Labels: development🔨, refactor♻️

#132 연동하면서 깨진 스타일 복원, 불필요한 스타일태그 링크 제거 등
  static/styles/page_styles/base_side.css
  static/styles/page_styles/base_side_right.css
  static/styles/page_styles/finished_routine.css
  static/styles/page_styles/make_friends_pages/friended.css
  static/styles/page_styles/make_friends_pages/friends_email_input.css
  static/styles/page_styles/onboarding_pages/last_menstruation_page.css
  static/styles/page_styles/onboarding_pages/onboarding_1.css
  static/styles/page_styles/onboarding_pages/onboarding_2.css
  static/styles/page_styles/onboarding_pages/purpose_page.css
  templates/example/base_side_right.html
  templates/pages/finished_routine.html
  templates/pages/make_friends_pages/friended.html
  templates/pages/make_friends_pages/friends_confirm.html
  templates/pages/make_friends_pages/friends_email_input.html
  templates/pages/onboarding_pages/last_menstruation_page.html
  templates/pages/onboarding_pages/login_page.html
  templates/pages/onboarding_pages/onboarding_1.html
  templates/pages/onboarding_pages/onboarding_2.html
  templates/pages/onboarding_pages/purpose_page.html
  templates/pages/onboarding_pages/signup_page.html
Labels: design💄, refactor♻️
